import React from "react";
import { NextPage } from "next";
import Head from "next/head";
import SideBar from "../SideBar";
import SearchBar from "../SearchBar";

interface LayoutProps {
  children: React.ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <div className="px-2 bg-white grid grid-cols-10">
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="col-span-2 border-r h-screen sticky top-0 ">
        <SideBar />
      </div>
      <div className="col-span-5 border-r"> {children}</div>
      <div className=" col-span-3 mx-4 py-2 h-screen sticky top-0">
        <SearchBar />
      </div>
    </div>
  );
};
export default Layout;
